Feature/eodhp 803 user can create metadata access policy
UKEODHP/stac-fastapi pull request #18
Opened 2024-11-26 23:13 UTC by tjellicoe-tpzuk

## Support Metadata Access Policy Updates

2024-11-27 15:58 UTC, ahaywardtvuk requested changes

2024-11-27 15:58 UTC, ahaywardtvuk commented on stac_fastapi/api/stac_fastapi/api/app.py
> +        default=attr.Factory(lambda: [BrotliMiddleware, ProxyHeaderMiddleware])
Unnecessary white-space changes will make it harder to merge changes from upstream or vice versa. For that reason we should stick with the code style from the original stac-fastapi and try to avoid changes which will make the diff larger.

2024-11-27 15:58 UTC, ahaywardtvuk commented on stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py
> +                self.client.update_catalog_access_control, PutCatalogStripped
This method isn't defined anywhere - should it be an abstract method added to core.py?

2024-11-27 15:58 UTC, ahaywardtvuk commented on stac_fastapi/api/stac_fastapi/api/app.py
> -    def register_get_collections(self):
Is this intended to be removed? Is there something somewhere else which still means that the `/collections` endpoints work?

2024-11-27 15:58 UTC, ahaywardtvuk commented on stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py
> +class PutCatalogStripped(CatalogUri):
What does 'Stripped' mean here? Is this really a 'put Catalog' operation rather then something to do with access control policies?

2024-11-28 08:57 UTC, tjellicoe-tpzuk commented on stac_fastapi/api/stac_fastapi/api/app.py
> +        default=attr.Factory(lambda: [BrotliMiddleware, ProxyHeaderMiddleware])
Updated

2024-11-28 09:06 UTC, tjellicoe-tpzuk commented on stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py
> +                self.client.update_catalog_access_control, PutCatalogStripped
Good point, added to types/core.py

2024-11-28 09:10 UTC, tjellicoe-tpzuk commented on stac_fastapi/api/stac_fastapi/api/app.py
> -    def register_get_collections(self):
Good spot, this is needed for the case where we don't use the `CollectionsSearch` extension, so was removed accidentally.

2024-11-28 09:21 UTC, tjellicoe-tpzuk commented on stac_fastapi/extensions/stac_fastapi/extensions/core/transaction.py
> +class PutCatalogStripped(CatalogUri):
Here I intended it to mean, without the additional catalog details that a normal catalog update request needs, but I can rename it to better reflect it's usage

2024-11-29 15:00 UTC, ahaywardtvuk approved these changes

2024-12-05 11:51 UTC, ahaywardtvuk approved these changes

2024-12-11 10:53 UTC, merged